### ISSUE TITLE
How to get the orient_R.npy in your provided data?

### ISSUE THREAD

**Issue by zhao-yiqun** [zjy526223908/DreamEditor#3]
Hi Jingyu

Thanks for your code sharing and preprocessed data. I have some question in your provided data.

Now I want to test DreamEditor on my custom data(some other cae on DTU dataset). However I found that in your implemetation, there is a file named as Orient_R.npy in all your provided data. I have checked your code and did not found how to get this Orient_R.npy from original dataset such as DTU etc.

I am wrting to ask what is the usage of the file and how can I get the file for my own data? 

Your reply is really important to me. Looking forward to your kind reply.

Thansk in Advance
Yiqun

**Comment by bbaaii** [comment]
hello，Yiqun
Do you know how to proccess custom data?

**Comment by bbaaii** [comment]
hello，Yiqun
Do you know how to proccess custom data?

**Comment by wunianguiguolu** [comment]
hello，Yiqun
Do you know how to proccess custom data?

**Comment by zhao-yiqun** [comment]
Hi @bbaaii @wunianguiguolu ,

Here is the reply from authors in chinese, maybe you can refer to it.


感谢你关注我们的工作。这个文件只是一个我自己定义的旋转矩阵终于矫正物体的朝向，使得物体正对方向为z轴，y轴垂直于地面向上。如果您使用自己的数据集，我建议你在meshlab软件中手动调整物体姿态并记录调整的姿态所需的旋转矩阵

**Comment by wunianguiguolu** [comment]
感谢回复，我想请教一下如何用DreamEditor跑自己的数据集？比如针对DreamEditor模型，跑一个不同于它预设的prompt？
----- 原始邮件 -----
发件人: "Yiqun Zhao" ***@***.***>
收件人: "zjy526223908/DreamEditor" ***@***.***>
抄送: "Chen Siyuan" ***@***.***>, "Mention" ***@***.***>
发送时间: 星期三, 2023年 11 月 08日 下午 10:05:53
主题: Re: [zjy526223908/DreamEditor] How to get the orient_R.npy in your provided data? (Issue #3)

Hi @bbaaii @wunianguiguolu ,

Here is the reply from authors in chinese, maybe you can refer to it.


感谢你关注我们的工作。这个文件只是一个我自己定义的旋转矩阵终于矫正物体的朝向，使得物体正对方向为z轴，y轴垂直于地面向上。如果您使用自己的数据集，我建议你在meshlab软件中手动调整物体姿态并记录调整的姿态所需的旋转矩阵
